# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.IntegerField(default=1)),
                ('catalog_id', models.IntegerField()),
                ('mob_logo', models.CharField(default='', max_length=200)),
                ('mob_url', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=50)),
                ('opt_uid', models.IntegerField(null=True)),
                ('pc_run_type', models.IntegerField(default=0)),
                ('pc_url', models.CharField(default='', max_length=200)),
                ('run_type', models.IntegerField(default=1)),
                ('summary', models.CharField(default='', max_length=100)),
                ('app_id', models.IntegerField()),
                ('author', models.CharField(default='', max_length=30)),
                ('mob_status', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '轻应用',
                'verbose_name_plural': '轻应用',
            },
        ),
        migrations.RenameField(
            model_name='app',
            old_name='app_id',
            new_name='portal_id',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_author',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='app',
            name='mob_logo',
        ),
        migrations.RemoveField(
            model_name='app',
            name='mob_status',
        ),
        migrations.RemoveField(
            model_name='app',
            name='mob_url',
        ),
        migrations.RemoveField(
            model_name='app',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='app',
            name='status',
        ),
        migrations.RemoveField(
            model_name='app',
            name='summary',
        ),
        migrations.AddField(
            model_name='portal_app',
            name='portal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
    ]
