# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180516_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_app',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
