# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180517_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal_app',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='portal_app',
            name='memberlist',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
