# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180517_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.IntegerField(default=1)),
                ('catalog_id', models.IntegerField()),
                ('mob_logo', models.CharField(default='', max_length=200)),
                ('mob_url', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('run_type', models.IntegerField(default=1)),
                ('summary', models.CharField(default='', max_length=100)),
                ('author_id', models.CharField(default='', max_length=30)),
                ('memberlist', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '轻应用',
                'verbose_name_plural': '轻应用',
            },
        ),
        migrations.AlterModelOptions(
            name='portal_app',
            options={'verbose_name': '应用', 'verbose_name_plural': '应用'},
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='catalog_id',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='memberlist',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='mob_logo',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='mob_url',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='portal_app',
            name='summary',
        ),
        migrations.AlterField(
            model_name='portal_app',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='portal_app',
            name='portal_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.AddField(
            model_name='light_app',
            name='portal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Portal_app'),
        ),
    ]
