# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180517_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portal_app',
            options={'verbose_name': '入口应用', 'verbose_name_plural': '入口应用'},
        ),
        migrations.AlterField(
            model_name='light_app',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
