# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='question',
            field=models.CharField(default='know', max_length=32),
        ),
    ]
