# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artical_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='question',
        ),
    ]
