# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_artical_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
