# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('portal_uid', models.IntegerField()),
                ('app_list', models.IntegerField()),
            ],
        ),
    ]
